server:
  port: 8080

spring:
  application:
    name: company_frame
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/company_frame?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456

      ##################   连接池配置   ################
      #连接池建立时创建的初始化连接数
      initial-size: 5
      #连接池中最大的活跃连接数
      max-active: 20
      #连接池中最小的活跃连接数
      min-idle: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 20
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      validation-query: SELECT 1 FROM DUAL
      query-timeout: 30000
      #是否在获得连接后检测其可用性
      test-on-borrow: false
      #是否在连接放回连接池后检测其可用性
      test-on-return: false
      #是否在连接空闲一段时间后检测其可用性
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat,wall
      #设置监控页面的登录名和密码
      stat-view-servlet:
        login-username: admin
        login-password: 666666
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    charset: UTF-8
    servlet:
      content-type: text/html
    cache: false


#logging配置
logging:
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: logs
  level:
    com.njust: debug

## mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.njust.entity
  configuration:
    map-underscore-to-camel-case: true
 ## 通过设置map-underscore-to-camel-case属性为true来开启驼峰功能

# 开启swagger2
swagger:
  enable: true


# redis配置
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（负数代表没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（负数代表没有限制）
        max-wait: PT10S
        # 连接池的最大空闲连接
        max-idle: 200
        # 连接池的最小空闲连接
        min-idle: 0
    # 连接超时时间
    timeout: PT10S


#JWT 密钥
jwt:
  secretKey: 78944878877848fg)
  accessTokenExpireTime: PT2H
  refreshTokenExpireTime: PT8H
  refreshTokenExpireAppTime: P30D
  issuer: njust.org.cn


